services:
  node-atomone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atomone-node
    ports:
      - "26656:26656"
    restart: unless-stopped
    volumes:
      - atomone_volume:/app/.atomone
      - ./entrypoint.sh:/app/entrypoint.sh

volumes:
  atomone_volume:
